spring.application.name=springBootAdmin1
server.port=8062

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true
spring.cloud.config.override-none=false


management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true