server:
  port: 8089

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/49d2b527-d999-453e-9ca1-ae9dd9284fc4/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/49d2b527-d999-453e-9ca1-ae9dd9284fc4/v2.0
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost"
              - "https://54.90.203.135"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:

        - id: inventory_service
          uri: lb://microservices-inventory
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1

        - id: order_service
          uri: lb://microservices-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

        - id: shipment_service
          uri: lb://microservices-shipment
          predicates:
            - Path=/api/shipment/**
          filters:
            - StripPrefix=1

        - id: bff_service
          uri: lb://microservices-bff
          predicates:
            - Path=/api/bff/**
          filters:
            - StripPrefix=1
