spring.application.name=keyCloakAdapter
server.port=8034
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

keycloak.base-uri=http://localhost:8091/auth/realms/
keycloak.authorization-uri=http://localhost:8091/realms/PaymentChain/protocol/openid-connect/auth
keycloak.user-info-uri=http://localhost:8091/realms/PaymentChain/protocol/openid-connect/userinfo
keycloak.token-uri=http://localhost:8091/realms/PaymentChain/protocol/openid-connect/token
keycloak.logout=http://localhost:8091/realms/PaymentChain/protocol/openid-connect/logout
keycloak.jwk-set-uri=http://localhost:8091/realms/PaymentChain/protocol/openid-connect/certs

keycloak.certs-id=r2RN6wtySEg9M_cnH4OoLFUWGn6oDOzxh9DAtJIwpmk
keycloak.client-id=front-client-app
keycloak.client-secret=qwerty
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

logging.level.root=INFO
